### ISSUE TITLE
'Complete Pear Setup' - not working

### ISSUE THREAD

**Issue by lukastanisic99** [holepunchto/pear#60]
Windows 10 and MacOS have the same problem - clicking the 'Complete Pear Setup' button doesn't work - nothing happens.

pear: 0.2494.pqbzjhqyonxprx8hghxexnmctw75mr91ewqw5dxe1zmntfyaddqy
bare: 1.0.0
uv: 1.48.0
v8: 11.8.172.16

**Comment by davidmarkclements** [comment]
might be a misunderstanding - it does work, it's just that you need to open a new terminal (or manually set your path in the terminal) for the system path to take effect, that's the model of the OS's though - we can't modify the path of a currently open terminal due to OS's security model. Closing for now but feel free to reopen if it's not related to old terminal
